import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import { fetchNewestList } from '@/api'
import Styles from '../styles/Home.module.scss'
import PageHead from '@/components/common/PageHead/index'
import ImgCard from '@/components/common/ImgCard'
import { Card, Row, Col } from 'antd';
// import { Button } from 'antd'

interface Props {
  // demo: String
  newestList: Array<Object>
}

const Home: NextPage<Props> = (props) => {
  const { newestList } = props
  console.log('----newestList', newestList)
  return (
    <div className={Styles.container}>
      <Head>
        <title>找表情 - 搞笑表情包 - 微信表情包 - QQ表情包 - 表情包制作 - 自制表情包 - gif表情包 - 找表情包 - emojivip.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main-container">
        <PageHead />
        <div className="main-content">
          <div className="left-content">
            <Card className="card-container" title="热门表情包" extra={<a href="#">更多</a>}>
              <Row gutter={[16, 16]}>
                {
                  newestList.map((item, index) => (
                    <Col className="aaa" key={index} span={6}>
                      <ImgCard imgItem={item}/>
                    </Col>
                  ))
                }
              </Row>
            </Card>
          </div>
          <div className="right-content">
            右边内容
          </div>
        </div>
      </main>

      <footer className={Styles.footer}>
        <div className={Styles['footer-inner']}></div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          {/* <span className={Styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  let newestList = []
  const { code, data } = await fetchNewestList({})
  if (code === 1) {
    newestList = data
  }
  return { props: { newestList } }
}


export default Home
