/*
 * @Descripttion: html头部组件
 * @Author: EdisonGu
 * @Date: 2022-04-29 11:31:20
 * @LastEditors: EdisonGu
 * @LastEditTime: 2022-04-29 11:38:58
 */
import React, { Component } from 'react'
import Head from 'next/head'

class HtmlHead extends Component {
  render() {
    return (
      <Head>
        <title>找表情 - 搞笑表情包 - 微信表情包 - QQ表情包 - 表情包制作 - 自制表情包 - gif表情包 - 找表情包 - emojivip.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
  }
}

export default HtmlHead