/*
 * @Descripttion: html头部组件
 * @Author: EdisonGu
 * @Date: 2022-04-29 11:31:20
 * @LastEditors: EdisonGu
 * @LastEditTime: 2022-04-29 11:38:58
 */
import React, { Component } from 'react'
import Head from 'next/head'
import { HTML_TITLE } from '@/constants/index'
interface Props {
  htmlTitle?: string
}
class HtmlHead extends Component<Props, any> {
  static defaultProps = {
    htmlTitle: ''
  }
  constructor(props: Props) {
    super(props)
  }
  render() {
    const { htmlTitle } = this.props
    return (
      <Head>
        <title>{htmlTitle ? htmlTitle : HTML_TITLE} - 表情逗 - emojivip.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
  }
}

export default HtmlHead